Feature login: página de login
igorgavilon/HelpperOriginsProjeto pull request #1
Opened 2021-11-25 19:25 UTC by igorgavilon

página de login, enviando os dados para o service de autenticação.
sem estilizações css.

2021-11-27 12:59 UTC, ErickHelpper approved these changes

2021-12-08 23:39 UTC, ErickHelpper requested changes

2021-12-08 23:39 UTC, ErickHelpper commented on src/app/@core/services/autenticacao.service.ts
> +    public login(dadosLogin: any): boolean {
Vou ignorar esse any por hora, na integração com o back vai precisar da interface aqui.

2021-12-08 23:39 UTC, ErickHelpper commented on src/app/@theme/components/input-senha/input-senha.component.scss
> +.input {
Esse estilo está se repetindo nos 2 componentes de input, nesse caso da pra criar um inputs.scss no mesmo nivel do styles.scss e importar ele no styles.scss usando o @import './inputs', caso tenha dúvida explico melhor em call 👍

2021-12-08 23:39 UTC, ErickHelpper commented on src/app/@theme/components/input-senha/input-senha.component.ts
> +export class MyErrorStateMatcher implements ErrorStateMatcher {
Não utilizar 2 classes no mesmo arquivo, pode separar essa classe aqui e deixar no mesmo nível do input. Também precisa colocar um nome mais descritivo nela.

2021-12-08 23:39 UTC, ErickHelpper commented on src/app/@theme/components/input-senha/input-senha.component.ts
> +  senhaForm: FormGroup;
Colocar nível de acesso.

2021-12-08 23:39 UTC, ErickHelpper commented on src/app/@theme/components/input-senha/input-senha.component.ts
> +  matcher = new MyErrorStateMatcher();
Faltou nível de acesso aqui também, só pra lembrar eles são:
public: todas as classes podem acessar.
protected: apenas a própria classe e suas filhas podem acessar.
private: apenas a própria classe pode acessar.

Utilizar com sabedoria, se o atributo só é acessado aqui não tem porque deixar public, não que seja o caso.

2021-12-08 23:39 UTC, ErickHelpper commented on src/app/pages/login/login.component.ts
> +  public login(form: NgForm): void {
vai precisar encapsular a chamada do service em um try catch na integração, por hora pode deixar como ta.

2021-12-09 23:08 UTC, cauegraciolip commented on src/app/@theme/components/input-senha/input-senha.component.ts
> +export class MyErrorStateMatcher implements ErrorStateMatcher {
Essa segunda classe será retirada do código. Ela não tem funcionalidade.

2021-12-10 22:30 UTC, ErickHelpper approved these changes

2021-12-18 19:38 UTC, merged