Feature pagina listas: criação
igorgavilon/HelpperOriginsProjeto pull request #2
Opened 2021-11-30 03:11 UTC by igorgavilon

criação da page Listas:
-funcional
-com listagem de todas os membros com listas ativas
-finalização de lista ativa
-marcação e remoção de falta em uma lista ativa
- sem estilização css!!!

2021-12-09 23:05 UTC, ErickHelpper requested changes

2021-12-09 23:05 UTC, ErickHelpper commented on src/app/@core/common/classes/classe-item-lista-padrao.ts
> +    constructor() {
Porque está iniciando os atributos como null?

2021-12-09 23:05 UTC, ErickHelpper commented on src/app/@core/common/classes/classe-item-lista-padrao.ts
> +    public id_lista: number;
Os dados dessa interface e das outras deveriam ter sido alinhados com o pessoal do back, muito provavelmente os dados la estão com nomes diferentes, vai ter que ajustar depois na integração

2021-12-09 23:05 UTC, ErickHelpper commented on src/app/@theme/components/botao-status-falta/botao-status-falta.component.ts
> +    public botaoStatusClicado: EventEmitter<any> = new EventEmitter();
EventEmitter é um tipo generico, entre os <> vc coloca o que ele vai emitir, nesse caso é boolean e não any.
Tipos genéricos no typescript:
https://www.typescriptlang.org/docs/handbook/2/generics.html

2021-12-09 23:05 UTC, ErickHelpper commented on src/app/@theme/components/card-item-lista/card-item-lista.component.html
> +        <!-- <div class="valor">
Remover código comentado

2021-12-09 23:05 UTC, ErickHelpper commented on src/app/@theme/components/card-item-lista/card-item-lista.component.ts
> +    public _modoReadOnly: boolean;
Não entendi a lógica que esta usando de nomenclatura para colocar o _ no nome da variável

2021-12-09 23:05 UTC, ErickHelpper commented on src/app/@theme/components/card-item-lista/card-item-lista.component.ts
> +    public botaoStatusClicado: EventEmitter<any> = new EventEmitter();
Tipar o EventEmitter aqui também

2021-12-09 23:05 UTC, ErickHelpper commented on src/app/@theme/components/card-item-lista/card-item-lista.component.ts
> +      this.checkboxSelecionado = true;
Você pode iniciar variáveis na própria declaração dela pra não ficar sempre um onInit iniciando tudo, ou coloca uma função apenas pra iniciar as variáveis e aí chamaria a função no onInit, o que achar melhor.

2021-12-09 23:05 UTC, ErickHelpper commented on src/app/@theme/components/secondary-dark-button/secondary-dark-button.component.html
> +<!-- color: #E29578 -->
remover

2021-12-09 23:05 UTC, ErickHelpper commented on src/app/@theme/components/secondary-dark-button/secondary-dark-button.component.html
> +    <mat-icon>{{true ? 'close' : 'visibility'}}</mat-icon>
Sempre vai ser 'close' aqui, não?

2021-12-09 23:05 UTC, ErickHelpper commented on src/app/pages/pagina-listas/card-lista-total-faltas/card-lista-total-faltas.component.ts
> +    public acaoFinalizarLista: any;
Funções também podem ser tipadas, nesse caso ficaria assim:
acaoFinalizarLista: () => void;

https://www.typescriptlang.org/docs/handbook/2/functions.html

2021-12-09 23:05 UTC, ErickHelpper commented on src/app/pages/pagina-listas/card-membro-resumo-descontos/card-membro-resumo-descontos.component.html
> +            <p>Descontos: <span [ngClass]="_valor_descontos > 0 ? 'estilo-valor-negativo' : ''"><span *ngIf="_valor_descontos !== 0">-</span>R$ {{_valor_descontos}}</span> </p>
Tem muita coisa amontoada aqui, da pra separar pra melhorar a legibilidade.

2021-12-09 23:05 UTC, ErickHelpper commented on src/app/pages/pagina-listas/card-membro-resumo-descontos/card-membro-resumo-descontos.component.ts
> +    //public _valorDescontosAtualizado: number;
remove o comentário e essas linhas em branco

2021-12-09 23:05 UTC, ErickHelpper commented on src/app/pages/pagina-listas/pagina-listas.component.scss
> +.section-esquerda h3 {
é scss, vc não precisa ficar repetindo o section-esquerda, pode encadear, exemplo:
```
.section-esquerda {
    width: 30%;
    
    h3 {
       margin-left: 20px;
    }
}
```

Isso serve pra outros lugares onde ta sendo repetido a classe.

2021-12-09 23:05 UTC, ErickHelpper commented on src/app/pages/pagina-listas/pagina-listas.component.ts
> +    this._id_membro_selecionado = id_membro;
acredito que tenha criado vários atributos apenas para poder popular lá no html, não esta ruim, mas da pra deixar um objeto só e lá no html vc chamar "membro.id_membro" por exemplo, funciona normal

2021-12-16 04:56 UTC, igorgavilon commented on src/app/@core/common/classes/classe-item-lista-padrao.ts
> +    constructor() {
essa classe já foi removida em branch posterior.
a ideia era criar (no CRUD lista) uma nova lista com valores nulos e mandar para o formulário.

2021-12-16 04:57 UTC, igorgavilon commented on src/app/@core/common/classes/classe-item-lista-padrao.ts
> +    public id_lista: number;
ok! vamos verificar

2021-12-18 19:58 UTC, merged