Feature pagina lista estilo
igorgavilon/HelpperOriginsProjeto pull request #6
Opened 2021-12-14 02:47 UTC by cauegraciolip

Adicionado estilos ao cards, botoes, scroll das atividades. 

Talvez necessite revisitar a branch para juntar as página com o header.

2021-12-14 02:48 UTC, cauegraciolip commented
![](https://github.trello.services/images/mini-trello-icon.png) [Página Lista Atividade - Estilo](https://trello.com/c/ghu7TI2G/31-p%C3%A1gina-lista-atividade-estilo)

2021-12-16 23:02 UTC, ErickHelpper requested changes

2021-12-16 23:02 UTC, ErickHelpper commented on src/app/@core/common/interfaces/atividade.interface.ts
> +/* eslint-disable semi */
Não dar disable no eslint, o lint ta aqui pra deixar o código padronizado, você deve seguir as regras dele.

2021-12-16 23:02 UTC, ErickHelpper commented on src/app/@core/common/interfaces/item-lista.interface.ts
> +// eslint-disable-next-line semi
Remover eslint disable

2021-12-16 23:02 UTC, ErickHelpper commented on src/app/@core/common/interfaces/lista-atividades.interface.ts
> +// eslint-disable-next-line semi
Remover eslint disable

2021-12-16 23:02 UTC, ErickHelpper commented on src/app/@theme/components/card-item-lista/card-item-lista.component.html
> +        <!-- <div class="input-valor" [hidden]="!checkboxSelecionado">
Não deixar código comentado, pode remover.

2021-12-16 23:02 UTC, ErickHelpper commented on src/app/@theme/components/input-email/input-email.component.ts
> +  // constructor() { }
Pode remover.

2021-12-16 23:02 UTC, ErickHelpper commented on src/app/@theme/components/input-email/input-email.component.ts
> +  // ngOnInit(): void {
Pode remover.

2021-12-18 20:26 UTC, merged